### ISSUE TITLE
Can't build on Ubuntu 18.10

### ISSUE THREAD

**Issue by NatoBoram** [Zygo/bees#88]
I have followed the instructions [here](https://github.com/Zygo/bees/blob/master/docs/install.md#ubuntu-1604---1704) for Ubuntu 17.04 and couldn't build it on Ubuntu 18.10.

```log
$ sudo apt -y install build-essential btrfs-tools uuid-dev markdown && make
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'btrfs-progs' instead of 'btrfs-tools'
btrfs-progs is already the newest version (4.16.1-2ubuntu1).
build-essential is already the newest version (12.5ubuntu2).
uuid-dev is already the newest version (2.32-0.1ubuntu2).
markdown is already the newest version (1.0.1-10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

make PREFIX=/usr LIBEXEC_PREFIX=/usr/lib/bees ETC_PREFIX=/etc -C lib
make[1]: Entering directory '/home/nato/Documents/GitHub/bees/lib'
g++ -Wall -Wextra -Werror -O3 -I../include -fpic -D_FILE_OFFSET_BITS=64 -std=c++11 -Wold-style-cast  -M -MF .depends/extentwalker.dep -MT extentwalker.o extentwalker.cc
In file included from ../include/crucible/fs.h:9,
                 from extentwalker.cc:5:
../include/crucible/btrfs.h:17:10: fatal error: btrfs/ioctl.h: No such file or directory
 #include <btrfs/ioctl.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
Makefile:44: depends.mk: No such file or directory
make[1]: *** [Makefile:34: .depends/extentwalker.dep] Error 1
make[1]: Leaving directory '/home/nato/Documents/GitHub/bees/lib'
make: *** [Makefile:34: lib] Error 2
```

```yaml
OS: Ubuntu 18.10 x86_64 
Kernel: 4.18.0-11-generic 
Uptime: 12 hours, 8 mins 
Packages: 2123 (dpkg), 42 (snap) 
Shell: bash 4.4.19 
Resolution: 1920x1080 
DE: GNOME 3.30.1 
WM: GNOME Shell 
WM Theme: Adwaita 
Theme: Adwaita-dark [GTK2/3] 
Icons: Yaru [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i5-3570K (4) @ 3.800GHz 
GPU: NVIDIA GeForce GTX 660 Ti 
Memory: 4247MiB / 7921MiB 
```
